
# feedback.py
feedback_recommendations = {"Talking Support": {
        "low": "You scored lower than most people when it comes to talking about death and dying. You might not feel very confident talking about death yet and that’s completely okay. Try joining a group or workshop where people talk openly about end-of-life topics. It's a great way to build comfort. If you'd like to learn more, feel free to check out this link: https://youtu.be/MuNZmasUuVY",
        "similar": "Your score is about the same as most people’s. You're about as comfortable talking about death as most people. That's a solid place to be. Keep having open conversations when the opportunity comes up, it helps create a more supportive space for everyone. If you'd like to learn more, feel free to check out this link: https://youtu.be/MuNZmasUuVY",
        "high": "You scored higher than most people in talking about death and dying. You seem really comfortable talking about end-of-life matters. which is a real strength. Use that comfort to gently support others who may find these conversations difficult. You can help make these talks feel safer. Although you've scored highly, feel free to watch a quick refresher on this topic: https://youtu.be/MuNZmasUuVY",
    },
    "Hands-On Support": {
        "low": "You scored lower than others in hands-on care. You may not have had much experience helping someone physically at the end of life. That's very common. You could look into volunteering, or even just learn basic care skills, it can help build confidence over time. If you'd like to learn more, feel free to check the description of this video, where video resources for each question are located: https://youtu.be/XzKVulz2PV0" ,
        "similar": "Your score is in line with the average when it comes to hands-on support. You've had some hands-on experience, about the same as most people. Share what you've learned, and look for chances to build on your skills when you feel ready. If you'd like to learn more, feel free to check the description of this video, where video resources for each question are located: https://youtu.be/XzKVulz2PV0",
        "high": "You scored higher than most people in hands-on support. You've clearly had experience helping someone directly, and that's really valuable. Consider mentoring others or getting involved in your community's end-of-life care efforts. Your experience can make a difference. If you'd like to learn more, feel free to check the description of this video, where video resources for each question are located: https://youtu.be/XzKVulz2PV0",
    }, 
    "Experience": {
        "low": "You scored lower than others in experience with death and dying. You may not have had many personal or professional experiences with death or dying. Consider listening to others' stories, or gently reflect on your own feelings. That's a good starting point. If you feel uncomfortable with where you stand on this topic, feel free to watch this video link for some reassurance: https://youtu.be/vCImGBMMFFI",
        "similar": "Your experience score is about average. Your experiences are about average, enough to give you a sense of what death and dying can be like. Stay open to learning from your own experiences and those around you. It builds wisdom. If you still feel uncomfortable with where you stand on this topic, feel free to watch this video link for some reassurance: https://youtu.be/vCImGBMMFFI",
        "high": "You scored higher than others in experience. You've had more exposure to death and dying than most. That gives you valuable perspective. You might find yourself naturally supporting others, your lived experience is a real asset. "
    },
    "Practical Knowledge": {
        "low": "You scored lower than others in death-related knowledge. You might not feel very informed about end-of-life care or services right now. Learning even just a bit more like what options exist can help you feel more prepared and confident. Feel free to check out this link if you'd like to learn more on this topic: https://youtu.be/E6P8QxGxbJ8",
        "similar": "Your knowledge score is about the same as others. You've got a good, solid base of knowledge enough to understand what's going on. Keep asking questions and exploring. It'll help you and those you care about. If you'd like to double - check that you know most things on this topic, feel free to check out this link: https://youtu.be/E6P8QxGxbJ8",
        "high": "You scored higher than most people in knowledge about end-of-life matters. You know quite a lot about death-related matters. That's a powerful tool. Consider helping others understand what you've learned, many people are looking for someone who can guide them. If you'd like to double - check that you know most things on this topic, feel free to check out this link: https://youtu.be/E6P8QxGxbJ8"
    },
    "Community Support 1": {
        "low": "You scored lower than others in feeling supported by your community. You might feel like your community doesn't offer much support around death and dying. Think about ways you can connect with others, there may be more support out there than it seems. If you'd like to learn more, feel free to check out this link: https://youtu.be/bZHLUQXCDsE",
        "similar": "Your score is typical when it comes to perceived community support. Your experience with community support is similar to most people's. Look for ways to strengthen those ties, community can be a big help during difficult times. If you'd like to learn more, feel free to check out this link: https://youtu.be/bZHLUQXCDsE",
        "high": "You scored higher than most in community support. You feel like your community is pretty supportive, which is wonderful. Help keep that support going by getting involved and welcoming others in. If you'd like to learn more, feel free to check out this link: https://youtu.be/bZHLUQXCDsE"
    }, 
    "Community Support 2": {
        "low": "You scored lower in how engaged your community feels around end-of-life care. It might feel like your community isn't very involved in end-of-life care. You could explore local initiatives or even start conversations that help get more people engaged. If you'd like to learn more, feel free to check out this link:https://youtu.be/G4vyPACb3CA",
        "similar": "Your community engagement score is similar to most people's. Your community's involvement seems about average. Keep encouraging participation, it helps everyone feel less alone. If you'd like to learn more, feel free to check out this link:https://youtu.be/G4vyPACb3CA",
        "high": "You scored higher than others in community engagement. You feel your community really steps up when it comes to end-of-life care. You can help others feel confident joining in too, your example can inspire more engagement."
    },
    "Community (Overall)": {
        "low": "You scored lower than others overall in community-related support. You might not feel very supported by your community around death-related matters. See if there are community groups or events that can help build that support. Small actions make a big difference. If you'd like to learn more, feel free to check out this link: https://youtu.be/G4vyPACb3CA and https://youtu.be/bZHLUQXCDsE",
        "similar": "Your overall community score is similar to others. Your sense of community support is about the same as others. Keep showing up and being part of the conversation, it helps the whole community grow stronger. If you'd like to learn more, feel free to check out this link: https://youtu.be/G4vyPACb3CA and https://youtu.be/bZHLUQXCDsE",
        "high": "You scored higher than others in overall community support. You see your community as supportive and engaged around dying and grieving. That's a real strength. Share what's working, others might be looking for ideas to build similar support in their own communities."
    },
    "Death Literacy Index (Overall)": {
        "low": "You scored lower than others on the overall Death Literacy Index. You may not feel very comfortable or knowledgeable about death yet, but that can change with time. Start with one step, talk to someone, read something, or reflect on what death means to you. It all adds up. We advise checking out the video links provided in your feedback - its a good place to start.",
        "similar": "Your score is about average across all areas of death literacy. You're in a similar place to most people there's a good base, and room to grow. Keep learning, talking and staying open, it's a journey that grows with you. Feel free to check out the video links provided in your feedback - its a good place to start.",
        "high": "You scored higher than most people on the Death Literacy Index. You seem to have a strong level of comfort, knowledge, and experience. That's a real gift. Think about how you can support others on their journey, you have a lot to offer."
    }
}
